### ISSUE TITLE
paper cutting problem

### ISSUE THREAD

**Issue by atasismail** [IgorGZd/directprint#1]
You're getting prints from the printer, but it's not automatically cutting the paper. How can you solve this issue?

**Comment by IgorGZd** [comment]
You need to send the paper cutting code
For example: paperCut = [29, 86, 48] or paperCutAlt = [29, 86, 1, 49].
If you are using a POS printer, see instructions for all ESC/POS sequences.

**Comment by atasismail** [comment]
Could we not perform the cutting operation using only the directprint package? If so, could you provide an example?

**Comment by IgorGZd** [comment]
```
Future<String?> doPrintExample() async {
    final directprintPlugin = Directprint();

    final paperCut = [29, 86, 48];
    String data = "Direct print plugin test ...\n\n\n\n\n\n";

    List<int> enctxt = [];
    enctxt.addAll(data.codeUnits);
    enctxt.addAll(paperCut);

    Uint8List pdata = Uint8List.fromList(enctxt);

    String printer = 'EPSON TM-T20III Receipt';
    String job = 'Sample print';

    return await directprintPlugin.print(printer, job, pdata);
  }
```

**Comment by atasismail** [comment]
Problem solved, thank you very much
