### ISSUE TITLE
character issue

### ISSUE THREAD

**Issue by ismailatas** [IgorGZd/directprint#2]
I'm encountering some difficulties with Turkish characters. Could you please help me resolve this?

**Comment by IgorGZd** [comment]
This component is "low-level." Depending on your (POS) printer, it is necessary to first send an initialization for the character set you need, e.g., for 8859_2, and later convert the text you want to print into the corresponding set.

**Comment by atasismail** [comment]
How exactly to do it, I'm not quite sure. Could you please show me a small example?

**Comment by ismailatas** [comment]
For friends experiencing character issues:


// ESC/POS command for Code page 858

`List<int> enctxt = [];
enctxt.addAll([27, 116, 19]);`
This can solve the problem.
